namespace:
  name: staging

replicas: 1

image:
  repository: nginx
  tag: 1.18.0
  pullPolicy: IfNotPresent
  name: nginx-alpine

resources:
  cpu: 50m
  memory: 128Mi

service:
  type: ClusterIP
  port: 8111

configmapData: 1.18.0
