namespace:
  name: prod

replicas: 2

image:
  repository: nginx
  tag: 1.17.0
  pullPolicy: IfNotPresent
  name: nginx-alpine

resources:
  cpu: 70m
  memory: 256Mi

service:
  type: ClusterIP
  port: 8111

configmapData: 1.17.0
