namespace:
  name: demo

replicas: 3

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent
  name: nginx-alpine

resources:
  cpu: 50m
  memory: 256Mi

service:
  type: ClusterIP
  port: 8111

configmap:
  name: nginx-version
